# Generated by Django 3.2.9 on 2021-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-name',),
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
