# Generated by Django 3.2.9 on 2021-12-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
