# Generated by Django 3.2.9 on 2021-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='Your Bio Goes Here'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='buisness',
            field=models.CharField(default='your buisness name goes here', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.CharField(default='Your goal goes here', max_length=350),
        ),
    ]
